#!/usr/bin/env zsh

ulimit -c unlimited

setopt append_history
setopt no_inc_append_history
setopt no_share_history

setopt extended_glob # treat #, ~, and ^ as part of patterns for filename generation
setopt auto_cd # If you type foo, and it isn't a command, and it is a directory in your cdpath, go there
setopt cdablevarS # if argument to cd is the name of a parameter whose value is a valid directory, it will become the current directory
setopt pushd_ignore_dups # don't push multiple copies of the same directory onto the directory stack

setopt always_to_end # When completing from the middle of a word, move the cursor to the end of the word
setopt auto_menu # show completion menu on successive tab press. needs unsetop menu_complete to work
setopt auto_name_dirs # any parameter that is set to the absolute name of a directory immediately becomes a name for that directory
setopt complete_in_word # Allow completion from within a word/phrase
unsetopt menu_complete # do not autoselect the first completion entry

setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments

# beeping is annoying
unsetopt BEEP

