#!/usr/bin/env zsh

#
# ZSH startup script
#

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

#ZSH_THEME="robbyrussell"
#ZSH_THEME="agnoster"
#SOLARIZED_THEME="light"
#
## Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git sudo zsh-syntax-highlighting)

# User configuration

# PATH
source $ZDOTDIR/zsh-paths

source $ZSH/oh-my-zsh.sh

autoload -U compinit && compinit
autoload -U compinit && compinit
zmodload -i zsh/complist

source $ZDOTDIR/zsh-options
source $ZDOTDIR/zsh-aliases

# Turn on vi mode
bindkey -v
bindkey '^u' backward-kill-line

ulimit -c unlimited


if [[ "$OSTYPE" = darwin* ]]; then
    # Override oh-my-zsh's use of gls if it is available (see .oh-my-zsh/lib/theme-and-appearance.zsh)
    alias ls='ls -G'
    test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
else
#    test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi

# . /Users/tony/anaconda3/etc/profile.d/conda.sh  # commented out by conda initialize

# opam configuration
test -r /Users/tony/.opam/opam-init/init.zsh && . /Users/tony/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$ANACONDAHOME/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$ANACONDAHOME/etc/profile.d/conda.sh" ]; then
        . "$ANACONDAHOME/etc/profile.d/conda.sh"
    else
        export PATH="$ANACONDAHOME/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
